{{- range .Values.configData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{ .filename}}: |
{{- if kindIs "map" .data }}
{{ .data | toYaml | nindent 4 }}
{{- else }}
{{ .data | nindent 4 }}
{{- end }}
---
{{- end }}