apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }} 
  labels:
    app: {{ .Values.name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app: {{ .Values.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.name }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}          

          # RESOURCES
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          # ALL PROBES DEFINED HERE
          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.startupProbe }}
          startupProbe:
          {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          # END OF PROBES
          ports:
          {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{- end }}
          # ENV
          env:
            # env vars from chart 
            {{- if .Values.env }}
            {{ .Values.env | toYaml | nindent 12 }}
            {{- end }}
            # env vars from sercers
            {{- range .Values.secretEnv }}
            {{- $secretName := .name }}
            {{- range .values }}
            - name: {{ .value }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
          # END of env values
          # ADDING VOLUMES
          volumeMounts:
            {{- range .Values.persistence.localStorage.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- range .Values.configData }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- range .Values.existingVolumes.pvcs }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- range .Values.existingVolumes.configMaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}

      volumes:
        {{- range .Values.persistence.localStorage.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
        {{- end }}
        {{- range .Values.configData }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
        {{- range .Values.existingVolumes.pvcs }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{- range .Values.existingVolumes.configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}

