{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.localStorage.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: local-storage
  selector:
    matchLabels:
      local: {{ .name }}
{{- end }}
{{- end }}