image:
  repository: docker.io/ollama/ollama
  tag: latest 
  pullPolicy: Always

# add resources in case run too big model and starve host from resources
resources:
  requests:
    memory: "500Mi"
    cpu: "10m"
  limits:
    memory: "2Gi"
    cpu: "500m"

securityContext: 
  # allowPrivilegeEscalation: false
  # privileged: false
  # runAsNonRoot: true
  # runAsUser: 1001          
  # runAsGroup: 1001         
  capabilities:
    drop:
    - ALL

# want to store models somewhere so when pod restarts  don't need to redownload
persistence:
  storageClass: local-storage
  capacity: 50Gi
  localStorage:
    enabled: true
    path: /media/lab/cluster-storage/volumes/ollama
    
# if want to install open-webui using flux helm release custom resources
# need to have flux custom resources available on the cluster 
openWebUI:
  extraEnvVars:
    - name: OLLAMA_BASE_URL
      value: "http://ollama.services.svc.cluster.local"
  ollama:
    enabled: false
