# Base values  
name: appname
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

# Networking
ports: 
  - port: 80
    name: http
    protocol: TCP
  
service: 
  - protocol: TCP
    port: 80
    targetPort: 80

# istio virtual service 
istioIngress:
    enabled: true
    gateway: my-gateway
    port: 80
    hostSufix: "example.com"
