# Base values  
name: appname
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

strategy: RollingUpdate

imagePullSecrets: []

securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL

env: []
secretEnv: []

readinessProbe: {}
livenessProbe: {}
startupProbe: {}

resources: 
  requests:
    cpu: "128m"
    memory: 128Mi
  limits:
    cpu: "512m"
    memory: 512Mi

persistence:
  enabled: false
  localStorage:
    volumes: []

configData: []

# Networking
# will create container port and svc for same port
ports: 
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP


# istio virtual service 
istioIngress:
    enabled: true
    gateway: my-gateway     
    port: 8000
    domain: "example.com"  # will result in appname.example.com fqdn

existingVolumes:
  pvcs: []
  # - name: my-existing-pvc
  #   mountPath: /data
  configMaps: []
  # - name: my-existing-cm
  #   mountPath: /etc/config

strategy: RollingUpdate  # RollingUpdate or Recreate

podLabels: {}