{{- if .Values.istio.enabled }}
{{- range .Values.ports }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}-virtualservice
  namespace: istio-ingress
  labels:
    app: {{ $.Values.name }} 
spec:
  hosts:
    # Generates: grafana.example.com
    - "{{ .name }}.{{ $.Values.istio.domain }}"
  gateways:
    - {{ $.Values.istio.gateway | quote }}
  http:
    - route:
        - destination:
            # Points to your single Nginx Service
            host: "nginx-auth.{{ $.Release.Namespace }}.svc.cluster.local"
            port:
              number: {{ .port }}
{{- end }}
{{- end }}