apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  app: {{ .Values.name}}
  labels:
    app: {{ .Values.name }} 
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- range .Values.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}
    {{- end }}