# Base values  
name: nginx-auth
replicaCount: 1

# need init image in order to create nginx usename and password
initContainer:
  repository: httpd
  tag: alpine3.23
  pullPolicy: Always

image:
  repository: nginx
  tag: alpine3.23
  pullPolicy: Always

imagePullSecrets: []

securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL

# set env so can create a secret for nginx login 
secretEnv: 
  - name: auth-secret    # name of secret that will be used
    values:
    - key: "USER_NAME"   # inside secret
      value: "AUTH_USER" # inside pod
    - key: "USER_PASS"   # inside secret
      value: "AUTH_PASS" # inside pod

resources: 
  enabled: true 
  requests:
    cpu: "128m"
    memory: 128Mi
  limits:
    cpu: "512m"
    memory: 512Mi

routes: []
  # - name: grafana
  #   target: http://grafana.monitoring.svc.cluster.local:3000
  #   port: 3000        # pod port spec and svc port spec
  #   protocol: TCP 
     

# create istio virtual service or not
# will use .Values.routes to get all paths
# all routes will use same domain and gateway
istio:
  enabled: true
  gateway: my-gateway
  domain: example.com
