name: test-app

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP

istioIngress:
  enabled: false

persistence:
  enabled: true
  localStorage:
    nodeKey: node-role.kubernetes.io/control-plane
    volumes:
      - name: data
        mountPath: /data
        hostPath: /mnt/storage/data
        size: 5Gi

configData: []
env: []
secretEnv: []
