apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard 
  labels:
    app.kubernetes.io/name: adguard
    app: adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  template:
    metadata:
      labels:
        app: adguard
        app.kubernetes.io/name: adguard
    spec:      
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
          - sh
          - -c
          - |
              mkdir -p /opt/adguardhome/conf
              cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
          image: busybox
          imagePullPolicy: Always
          name: copy-configmap
          resources: 
            limits:
              memory: "64Mi"
              cpu: "20m"
          securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
          volumeMounts:
          - mountPath: /tmp/AdGuardHome.yaml
            name: adguard-home-config
            subPath: AdGuardHome.yaml
          - mountPath: /opt/adguardhome/conf
            name: config
      containers:
        {{- if .Values.logsSidecar.enabled }}
        - name: adguard-logs-collector
          image: "{{ .Values.sidecarImage.repository }}:{{ .Values.sidecarImage.tag }}"
          imagePullPolicy: {{ .Values.sidecarImage.pullPolicy }} 
          resources: 
            limits:
              memory: "16Mi"
              cpu: "32m"
          volumeMounts:
            - name: log
              mountPath:  /opt/adguardhome/work
            - name: sidecar-config
              mountPath: /fluent-bit/etc
        {{- end }}

        - name: adguard-home
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          resources: 
            limits:
              memory: "812Mi"
              cpu: "36m"
          args:
            - --config
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - --work-dir
            - /opt/adguardhome/work
            - --no-check-update
          env:
            - name: TZ
              value: {{ .Values.timeZone }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 3000
              protocol: TCP
          securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_BIND_SERVICE # Allows binding to ports 53
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
            
      {{- if .Values.logsSidecar.enabled }}    
          volumeMounts:
            - name: adguard-home-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            - name: config
              mountPath: /opt/adguardhome/conf
            - name: log
              mountPath: /opt/adguardhome/work/
      volumes:
        - name: adguard-home-config
          configMap:
            name: adguard-config 
        - name: config
          emptyDir: {}
        - name: log
          emptyDir: {}
        - name: sidecar-config
          configMap:
            name: {{ .Values.logsSidecar.configName }} 
      {{- end }}
