apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard 
  labels:
    app.kubernetes.io/name: adguard
    app: adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  template:
    metadata:
      labels:
        app: adguard
        app.kubernetes.io/name: adguard
    spec:      
      automountServiceAccountToken: false
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      dnsPolicy: ClusterFirst
      {{- end }}
      initContainers:
        - name: copy-configmap
          command: ["sh", "-c"]
          args:
          - |
{{- .Values.copyConfigScript.args | nindent 12 }}
          image: busybox
          imagePullPolicy: Always
          resources: 
            limits:
              memory: "64Mi"
              cpu: "20m"
          securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
          volumeMounts:
          # cm mounts config
          - mountPath: /tmp/AdGuardHome.yaml
            name: adguard-home-config
            subPath: AdGuardHome.yaml
          # config that is added to adguard
          - mountPath: /opt/adguardhome/conf
            name: shared-config
      containers:
        {{- if .Values.logsSidecar.enabled }}
        - name: adguard-logs-collector
          image: "{{ .Values.sidecarImage.repository }}:{{ .Values.sidecarImage.tag }}"
          imagePullPolicy: {{ .Values.sidecarImage.pullPolicy }} 
          resources: 
            limits:
              memory: "16Mi"
              cpu: "32m"
          volumeMounts:
            # logs file
            - name: log-share
              mountPath:  /opt/adguardhome/work
            # logs scrape config
            - name: logs-sidecar-config
              mountPath: /fluent-bit/etc
        {{- end }}

        - name: adguard-home
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          resources: 
            limits:
              memory: "812Mi"
              cpu: "36m"
          args:
            - --config
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - --work-dir
            - /opt/adguardhome/work
            - --no-check-update
          env:
            - name: TZ
              value: {{ .Values.timeZone }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: {{ .Values.probes.port }}
              protocol: TCP
          securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_BIND_SERVICE # Allows binding to ports 53
          livenessProbe:
            tcpSocket:            
              {{- if .Values.hostNetwork}}
              host: 127.0.0.1
              {{- end }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:            
              {{- if .Values.hostNetwork}}
              host: 127.0.0.1
              {{- end }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:            
              {{- if .Values.hostNetwork}}
              host: 127.0.0.1
              {{- end }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
            
          volumeMounts:
            - name: adguard-home-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            # shared config from init container  
            - name: shared-config
              mountPath: /opt/adguardhome/conf
            # shared mount between fluentBit and adguard
            {{- if .Values.logsSidecar.enabled }}    
            - name: log-share
              mountPath: /opt/adguardhome/work/
            {{- end }}
            # ssl config
            {{- if .Values.ssl.enabled }}
            - name: ssl
              mountPath: /opt/adguardhome/ssl
              readOnly: true
            {{- end }}
      volumes:
      # sharing config between init container and main container
        - name: adguard-home-config
          configMap:
            name: adguard-config
      # ssl certs for https
      {{- if .Values.ssl.enabled }}
        - name: ssl
          secret:
            secretName: adguard-ssl
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      {{- end }}
      # store config persistently
        - name: shared-config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: adguard-pvc 
          {{- else }}
          emptyDir: {}
          {{- end }}
        # fluentBit config and shared log file
        {{- if .Values.logsSidecar.enabled }}    
        - name: log-share
          emptyDir: {}
        - name: logs-sidecar-config
          configMap:
            name: {{ .Values.logsSidecar.configName }} 
        {{- end }}

