apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly
  labels:
    local: gitlab-gitaly
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path: {{ .Values.global.storagePath}}/gitlab/gitlab-gitaly
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql
  labels:
    local: gitlab-postgresql
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path: {{ .Values.global.storagePath}}/gitlab/gitlab-postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio
  labels:
    local: gitlab-minio
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path: {{ .Values.global.storagePath}}/gitlab/gitlab-minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis
  labels:
    local:  gitlab-redis
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path:  {{ .Values.global.storagePath}}/gitlab/gitlab-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true"           