global:
  storagePath: ""
  istio:
    enabled: true
  domain:
    internal: 
      url: ""
      gateway: ""
    internalTls:
      url: ""
      gateway: ""
    external: 
      url: ""
      gateway: ""

gitlab:
  enabled: true
runner:
  enabled: true 